export const HOTEL_ICONS: { icon: string; label: string }[] = [
  { icon: 'hotel', label: 'Hotel' },
  { icon: 'local_hotel', label: 'Alojamiento' },
  { icon: 'meeting_room', label: 'Habitación / Sala' },
  { icon: 'no_meeting_room', label: 'Sin sala' },
  { icon: 'free_breakfast', label: 'Desayuno incluido' },
  { icon: 'all_inclusive', label: 'Todo incluido' },
  { icon: 'room_service', label: 'Servicio a la habitación' },
  { icon: 'kitchen', label: 'Cocina equipada' },
  { icon: 'ac_unit', label: 'Aire acondicionado' },
  { icon: 'spa', label: 'Spa / Masajes' },
  { icon: 'pool', label: 'Piscina' },
  { icon: 'fitness_center', label: 'Gimnasio' },
  { icon: 'hot_tub', label: 'Jacuzzi / Tina' },
  { icon: 'beach_access', label: 'Playa / Sombrillas' },
  { icon: 'golf_course', label: 'Golf' },
  { icon: 'casino', label: 'Casino / Entretenimiento' },
  { icon: 'business_center', label: 'Centro de negocios' },
  { icon: 'child_care', label: 'Cuidado de niños' },
  { icon: 'child_friendly', label: 'Área para niños' },
  { icon: 'smoke_free', label: 'Libre de humo' },
  { icon: 'smoking_rooms', label: 'Área fumadores' },
  { icon: 'rv_hookup', label: 'Conexión RV' },
  { icon: 'restaurant', label: 'Restaurante' },
  { icon: 'restaurant_menu', label: 'Menú / Carta' },
  { icon: 'local_dining', label: 'Comedor' },
  { icon: 'local_cafe', label: 'Cafetería' },
  { icon: 'local_bar', label: 'Bar / Salón' },
  { icon: 'local_pizza', label: 'Snacks / Comida rápida' },
  { icon: 'local_drink', label: 'Bebidas' },
  { icon: 'fastfood', label: 'Comida al paso' },
  { icon: 'local_florist', label: 'Jardín / Flores' },
  { icon: 'local_parking', label: 'Estacionamiento' },
  { icon: 'local_laundry_service', label: 'Lavandería' },
  { icon: 'local_atm', label: 'Cajero / ATM' },
  { icon: 'local_printshop', label: 'Impresión / Fax' },
  { icon: 'local_airport', label: 'Transporte aeropuerto' },
  { icon: 'airport_shuttle', label: 'Shuttle / Transfer' },
  { icon: 'local_taxi', label: 'Taxi' },
  { icon: 'local_gas_station', label: 'Gasolinera' },
  { icon: 'local_grocery_store', label: 'Tienda / Mercado' },
  { icon: 'local_pharmacy', label: 'Farmacia' },
  { icon: 'local_hospital', label: 'Asistencia médica' },
  { icon: 'local_library', label: 'Biblioteca' },
  { icon: 'local_mall', label: 'Centro comercial' },
  { icon: 'local_movies', label: 'Cine' },
  { icon: 'local_offer', label: 'Oferta especial' },
  { icon: 'local_play', label: 'Entretenimiento local' },
  { icon: 'local_post_office', label: 'Correo / Envíos' },
  { icon: 'local_shipping', label: 'Envíos' },
  { icon: 'local_see', label: 'Buceo / Snorkel' },
  { icon: 'local_activity', label: 'Actividades' },
  { icon: 'local_phone', label: 'Teléfono local' },
  { icon: 'local_car_wash', label: 'Lavado de autos' },
  { icon: 'local_convenience_store', label: 'Tienda de conveniencia' },
  { icon: 'ev_station', label: 'Carga eléctrica' },
  { icon: 'directions_car', label: 'Transporte privado' },
  { icon: 'directions_bus', label: 'Bus / Shuttle' },
  { icon: 'directions_bike', label: 'Bicicletas' },
  { icon: 'directions_run', label: 'Jogging / Running' },
  { icon: 'directions_walk', label: 'Caminatas' },
  { icon: 'directions_boat', label: 'Embarcaciones / Bote' },
  { icon: 'directions_railway', label: 'Tren / Ferrocarril' },
  { icon: 'directions_subway', label: 'Metro' },
  { icon: 'directions_transit', label: 'Transporte público' },
  { icon: 'directions', label: 'Indicaciones' },
  { icon: 'flight', label: 'Vuelos' },
  { icon: 'train', label: 'Tren' },
  { icon: 'subway', label: 'Metro / Subterráneo' },
  { icon: 'tram', label: 'Tranvía' },
  { icon: 'terrain', label: 'Senderismo / Trekking' },
  { icon: 'landscape', label: 'Paisaje / Vista' },
  { icon: 'explore', label: 'Exploración / Tours' },
  { icon: 'map', label: 'Mapa' },
  { icon: 'place', label: 'Lugar' },
  { icon: 'location_on', label: 'Ubicación' },
  { icon: 'location_off', label: 'Sin ubicación' },
  { icon: 'near_me', label: 'Cerca de mí' },
  { icon: 'my_location', label: 'Mi ubicación' },
  { icon: 'pin_drop', label: 'Marcar punto' },
  { icon: 'navigation', label: 'Navegación' },
  { icon: 'beenhere', label: 'Visitado' },
  { icon: 'atm', label: 'Cajero automático' },
  { icon: 'satellite', label: 'Vista satélite' },
  { icon: 'streetview', label: 'Vista calle' },
  { icon: 'rate_review', label: 'Calificación / Reseña' },
  { icon: 'add_location', label: 'Agregar ubicación' },
  { icon: 'edit_location', label: 'Editar ubicación' },
  { icon: 'traffic', label: 'Tráfico' },
  { icon: 'category', label: 'Categoría' },
  { icon: 'money', label: 'Dinero' },
  { icon: 'store_mall_directory', label: 'Directorio de tiendas' },
  { icon: 'departure_board', label: 'Tablero de salidas' },
  { icon: 'transfer_within_a_station', label: 'Conexión en estación' },
  { icon: 'transit_enterexit', label: 'Entrada/Salida transporte' },
  { icon: 'trip_origin', label: 'Origen del viaje' },
  { icon: 'zoom_out_map', label: 'Ampliar mapa' },
  { icon: 'compass_calibration', label: 'Calibrar brújula' },
  { icon: '360', label: 'Vista 360°' },
  { icon: 'accessibility', label: 'Accesibilidad' },
  { icon: 'accessibility_new', label: 'Accesibilidad nueva' },
  { icon: 'accessible', label: 'Acceso especial' },
  { icon: 'accessible_forward', label: 'Acceso hacia adelante' },
  { icon: 'account_balance', label: 'Banco / Finanzas' },
  { icon: 'account_balance_wallet', label: 'Billetera' },
  { icon: 'account_box', label: 'Perfil cuadro' },
  { icon: 'account_circle', label: 'Perfil círculo' },
  { icon: 'add_shopping_cart', label: 'Agregar al carrito' },
  { icon: 'alarm', label: 'Alarma' },
  { icon: 'alarm_add', label: 'Agregar alarma' },
  { icon: 'alarm_off', label: 'Alarma apagada' },
  { icon: 'alarm_on', label: 'Alarma encendida' },
  { icon: 'all_out', label: 'Todo afuera' },
  { icon: 'announcement', label: 'Anuncio' },
  { icon: 'arrow_right_alt', label: 'Flecha derecha' },
  { icon: 'aspect_ratio', label: 'Relación de aspecto' },
  { icon: 'assessment', label: 'Evaluación' },
  { icon: 'assignment', label: 'Asignación' },
  { icon: 'assignment_ind', label: 'Asignación individual' },
  { icon: 'assignment_late', label: 'Asignación tardía' },
  { icon: 'assignment_return', label: 'Devolución' },
  { icon: 'assignment_returned', label: 'Devuelto' },
  { icon: 'assignment_turned_in', label: 'Entregado' },
  { icon: 'autorenew', label: 'Renovar automáticamente' },
  { icon: 'backup', label: 'Respaldo' },
  { icon: 'book', label: 'Libro' },
  { icon: 'bookmark', label: 'Marcador' },
  { icon: 'bookmark_border', label: 'Marcador borde' },
  { icon: 'bug_report', label: 'Reporte de error' },
  { icon: 'build', label: 'Construcción / Mantenimiento' },
  { icon: 'cached', label: 'Caché' },
  { icon: 'calendar_today', label: 'Calendario hoy' },
  { icon: 'calendar_view_day', label: 'Vista día' },
  { icon: 'camera_enhance', label: 'Cámara mejorada' },
  { icon: 'card_giftcard', label: 'Tarjeta regalo' },
  { icon: 'card_membership', label: 'Membresía' },
  { icon: 'card_travel', label: 'Viaje / Paquetes' },
  { icon: 'change_history', label: 'Historial de cambios' },
  { icon: 'check_circle', label: 'Verificado' },
  { icon: 'check_circle_outline', label: 'Verificado contorno' },
  { icon: 'chrome_reader_mode', label: 'Modo lectura' },
  { icon: 'class', label: 'Clase' },
  { icon: 'code', label: 'Código' },
  { icon: 'commute', label: 'Transporte compartido' },
  { icon: 'compare_arrows', label: 'Comparar' },
  { icon: 'contact_support', label: 'Soporte' },
  { icon: 'copyright', label: 'Derechos de autor' },
  { icon: 'credit_card', label: 'Tarjeta de crédito' },
  { icon: 'dashboard', label: 'Panel de control' },
  { icon: 'date_range', label: 'Rango de fechas' },
  { icon: 'delete', label: 'Eliminar' },
  { icon: 'delete_forever', label: 'Eliminar para siempre' },
  { icon: 'delete_outline', label: 'Eliminar contorno' },
  { icon: 'description', label: 'Descripción / Documento' },
  { icon: 'dns', label: 'DNS / Servidor' },
  { icon: 'done', label: 'Listo' },
  { icon: 'done_all', label: 'Todo listo' },
  { icon: 'done_outline', label: 'Listo contorno' },
  { icon: 'donut_large', label: 'Donut grande' },
  { icon: 'donut_small', label: 'Donut pequeño' },
  { icon: 'drag_indicator', label: 'Arrastrar' },
  { icon: 'euro_symbol', label: 'Euro' },
  { icon: 'event', label: 'Evento' },
  { icon: 'event_seat', label: 'Asiento de evento' },
  { icon: 'exit_to_app', label: 'Salir de la app' },
  { icon: 'extension', label: 'Extensión' },
  { icon: 'face', label: 'Rostro / Persona' },
  { icon: 'favorite', label: 'Favorito' },
  { icon: 'favorite_border', label: 'Favorito contorno' },
  { icon: 'feedback', label: 'Retroalimentación' },
  { icon: 'find_in_page', label: 'Buscar en página' },
  { icon: 'find_replace', label: 'Buscar y reemplazar' },
  { icon: 'fingerprint', label: 'Huella digital' },
  { icon: 'flight_land', label: 'Aterrizaje' },
  { icon: 'flight_takeoff', label: 'Despegue' },
  { icon: 'flip_to_back', label: 'Mover atrás' },
  { icon: 'flip_to_front', label: 'Mover adelante' },
  { icon: 'g_translate', label: 'Traducción' },
  { icon: 'gavel', label: 'Martillo / Legislación' },
  { icon: 'get_app', label: 'Descargar app' },
  { icon: 'gif', label: 'GIF animado' },
  { icon: 'grade', label: 'Calificación / Estrella' },
  { icon: 'group_work', label: 'Trabajo en grupo' },
  { icon: 'help', label: 'Ayuda' },
  { icon: 'help_outline', label: 'Ayuda contorno' },
  { icon: 'highlight_off', label: 'Resaltado apagado' },
  { icon: 'history', label: 'Historial' },
  { icon: 'home', label: 'Inicio / Hogar' },
  { icon: 'horizontal_split', label: 'División horizontal' },
  { icon: 'hourglass_empty', label: 'Reloj arena vacío' },
  { icon: 'hourglass_full', label: 'Reloj arena lleno' },
  { icon: 'http', label: 'HTTP' },
  { icon: 'https', label: 'HTTPS / Seguro' },
  { icon: 'important_devices', label: 'Dispositivos importantes' },
  { icon: 'info', label: 'Información' },
  { icon: 'input', label: 'Entrada' },
  { icon: 'invert_colors', label: 'Invertir colores' },
  { icon: 'label', label: 'Etiqueta' },
  { icon: 'label_important', label: 'Etiqueta importante' },
  { icon: 'language', label: 'Idioma / Multilingüe' },
  { icon: 'launch', label: 'Lanzar / Abrir' },
  { icon: 'line_style', label: 'Estilo de línea' },
  { icon: 'line_weight', label: 'Peso de línea' },
  { icon: 'list', label: 'Lista' },
  { icon: 'lock', label: 'Candado / Caja fuerte' },
  { icon: 'lock_open', label: 'Candado abierto' },
  { icon: 'loyalty', label: 'Lealtad / Programa' },
  { icon: 'markunread_mailbox', label: 'Buzón sin leer' },
  { icon: 'maximize', label: 'Maximizar' },
  { icon: 'minimize', label: 'Minimizar' },
  { icon: 'motorcycle', label: 'Motocicleta' },
  { icon: 'note_add', label: 'Agregar nota' },
  { icon: 'offline_bolt', label: 'Rayo sin conexión' },
  { icon: 'offline_pin', label: 'Pin sin conexión' },
  { icon: 'opacity', label: 'Opacidad' },
  { icon: 'open_in_browser', label: 'Abrir en navegador' },
  { icon: 'open_in_new', label: 'Abrir en nueva ventana' },
  { icon: 'open_with', label: 'Abrir con' },
  { icon: 'pageview', label: 'Vista de página' },
  { icon: 'pan_tool', label: 'Mano / Pausa' },
  { icon: 'payment', label: 'Pago' },
  { icon: 'perm_camera_mic', label: 'Permiso cámara/micrófono' },
  { icon: 'perm_contact_calendar', label: 'Permiso contactos' },
  { icon: 'perm_data_setting', label: 'Configuración de datos' },
  { icon: 'perm_device_information', label: 'Info del dispositivo' },
  { icon: 'perm_identity', label: 'Identidad' },
  { icon: 'perm_media', label: 'Permiso multimedia' },
  { icon: 'perm_phone_msg', label: 'Permiso teléfono' },
  { icon: 'perm_scan_wifi', label: 'Escanear WiFi' },
  { icon: 'pets', label: 'Mascotas bienvenidas' },
  { icon: 'picture_in_picture', label: 'Imagen en imagen' },
  { icon: 'picture_in_picture_alt', label: 'Imagen en imagen alt' },
  { icon: 'play_for_work', label: 'Trabajo / Descargar' },
  { icon: 'power_settings_new', label: 'Encender/Apagar' },
  { icon: 'print', label: 'Imprimir' },
  { icon: 'query_builder', label: 'Consulta / Horario' },
  { icon: 'question_answer', label: 'Preguntas y respuestas' },
  { icon: 'receipt', label: 'Recibo' },
  { icon: 'record_voice_over', label: 'Grabación de voz' },
  { icon: 'redeem', label: 'Canjear / Promociones' },
  { icon: 'remove_shopping_cart', label: 'Quitar del carrito' },
  { icon: 'reorder', label: 'Reordenar' },
  { icon: 'report_problem', label: 'Reportar problema' },
  { icon: 'restore', label: 'Restaurar' },
  { icon: 'restore_from_trash', label: 'Restaurar de papelera' },
  { icon: 'restore_page', label: 'Restaurar página' },
  { icon: 'room', label: 'Habitación / Lugar' },
  { icon: 'rounded_corner', label: 'Esquina redondeada' },
  { icon: 'rowing', label: 'Remo / Kayak' },
  { icon: 'schedule', label: 'Horario' },
  { icon: 'search', label: 'Buscar' },
  { icon: 'security', label: 'Seguridad 24h' },
  { icon: 'settings', label: 'Configuración' },
  { icon: 'settings_applications', label: 'Configuración apps' },
  { icon: 'settings_backup_restore', label: 'Respaldo/Restaurar' },
  { icon: 'settings_bluetooth', label: 'Bluetooth' },
  { icon: 'settings_brightness', label: 'Brillo' },
  { icon: 'settings_cell', label: 'Datos móviles' },
  { icon: 'settings_ethernet', label: 'Ethernet' },
  { icon: 'settings_input_antenna', label: 'Antena' },
  { icon: 'settings_input_component', label: 'Componente de entrada' },
  { icon: 'settings_input_composite', label: 'Entrada compuesta' },
  { icon: 'settings_input_hdmi', label: 'HDMI' },
  { icon: 'settings_input_svideo', label: 'S-Video' },
  { icon: 'settings_overscan', label: 'Overscan' },
  { icon: 'settings_phone', label: 'Configuración teléfono' },
  { icon: 'settings_power', label: 'Configuración energía' },
  { icon: 'settings_remote', label: 'Control remoto' },
  { icon: 'settings_voice', label: 'Configuración voz' },
  { icon: 'shop', label: 'Tienda' },
  { icon: 'shop_two', label: 'Tienda dos' },
  { icon: 'shopping_basket', label: 'Cesta de compras' },
  { icon: 'shopping_cart', label: 'Carrito de compras' },
  { icon: 'speaker_notes', label: 'Notas del orador' },
  { icon: 'speaker_notes_off', label: 'Notas desactivadas' },
  { icon: 'spellcheck', label: 'Corrección ortográfica' },
  { icon: 'stars', label: 'Calidad Premium' },
  { icon: 'store', label: 'Tienda / Negocio' },
  { icon: 'subject', label: 'Asunto / Texto' },
  { icon: 'supervised_user_circle', label: 'Usuario supervisado' },
  { icon: 'supervisor_account', label: 'Supervisor' },
  { icon: 'swap_horiz', label: 'Intercambiar horizontal' },
  { icon: 'swap_horizontal_circle', label: 'Intercambiar horizontal círculo' },
  { icon: 'swap_vert', label: 'Intercambiar vertical' },
  { icon: 'swap_vertical_circle', label: 'Intercambiar vertical círculo' },
  { icon: 'tab', label: 'Pestaña' },
  { icon: 'tab_unselected', label: 'Pestaña no seleccionada' },
  { icon: 'text_rotate_up', label: 'Texto rotar arriba' },
  { icon: 'text_rotate_vertical', label: 'Texto rotar vertical' },
  { icon: 'text_rotation_down', label: 'Texto rotación abajo' },
  { icon: 'text_rotation_none', label: 'Texto sin rotación' },
  { icon: 'theaters', label: 'Teatro / Shows' },
  { icon: 'thumb_down', label: 'No recomendado' },
  { icon: 'thumb_up', label: 'Recomendado' },
  { icon: 'thumbs_up_down', label: 'Calificación mixta' },
  { icon: 'timeline', label: 'Línea de tiempo' },
  { icon: 'toc', label: 'Tabla de contenido' },
  { icon: 'today', label: 'Hoy' },
  { icon: 'toll', label: 'Peaje' },
  { icon: 'touch_app', label: 'Toque de app' },
  { icon: 'track_changes', label: 'Rastrear cambios' },
  { icon: 'translate', label: 'Traducir' },
  { icon: 'trending_down', label: 'Tendencia a la baja' },
  { icon: 'trending_flat', label: 'Tendencia plana' },
  { icon: 'trending_up', label: 'Tendencia al alza' },
  { icon: 'turned_in', label: 'Guardado' },
  { icon: 'turned_in_not', label: 'No guardado' },
  { icon: 'update', label: 'Actualizar' },
  { icon: 'verified_user', label: 'Usuario verificado' },
  { icon: 'vertical_split', label: 'División vertical' },
  { icon: 'view_agenda', label: 'Vista agenda' },
  { icon: 'view_array', label: 'Vista arreglo' },
  { icon: 'view_carousel', label: 'Vista carrusel' },
  { icon: 'view_column', label: 'Vista columna' },
  { icon: 'view_day', label: 'Vista día' },
  { icon: 'view_headline', label: 'Vista titular' },
  { icon: 'view_list', label: 'Vista lista' },
  { icon: 'view_module', label: 'Vista módulo' },
  { icon: 'view_quilt', label: 'Vista mosaico' },
  { icon: 'view_stream', label: 'Vista flujo' },
  { icon: 'view_week', label: 'Vista semana' },
  { icon: 'visibility', label: 'Visibilidad' },
  { icon: 'visibility_off', label: 'Ocultar' },
  { icon: 'voice_over_off', label: 'Voz apagada' },
  { icon: 'watch_later', label: 'Ver más tarde' },
  { icon: 'work', label: 'Trabajo' },
  { icon: 'work_off', label: 'Sin trabajo' },
  { icon: 'work_outline', label: 'Trabajo contorno' },
  { icon: 'zoom_in', label: 'Acercar' },
  { icon: 'zoom_out', label: 'Alejar' },
  { icon: 'alternate_email', label: 'Email alternativo' },
  { icon: 'business', label: 'Empresa / Negocio' },
  { icon: 'call', label: 'Llamada' },
  { icon: 'call_end', label: 'Colgar' },
  { icon: 'call_made', label: 'Llamada saliente' },
  { icon: 'call_merge', label: 'Combinar llamadas' },
  { icon: 'call_missed', label: 'Llamada perdida' },
  { icon: 'call_missed_outgoing', label: 'Saliente perdida' },
  { icon: 'call_received', label: 'Llamada recibida' },
  { icon: 'call_split', label: 'Separar llamada' },
  { icon: 'cancel_presentation', label: 'Cancelar presentación' },
  { icon: 'cell_wifi', label: 'WiFi celular' },
  { icon: 'chat', label: 'Chat / Atención' },
  { icon: 'chat_bubble', label: 'Burbuja de chat' },
  { icon: 'chat_bubble_outline', label: 'Burbuja contorno' },
  { icon: 'clear_all', label: 'Limpiar todo' },
  { icon: 'comment', label: 'Comentario' },
  { icon: 'contact_mail', label: 'Correo de contacto' },
  { icon: 'contact_phone', label: 'Teléfono de contacto' },
  { icon: 'contacts', label: 'Contactos' },
  { icon: 'dialer_sip', label: 'Marcador SIP' },
  { icon: 'dialpad', label: 'Teclado de marcado' },
  { icon: 'domain_disabled', label: 'Dominio deshabilitado' },
  { icon: 'email', label: 'Email / Contacto' },
  { icon: 'forum', label: 'Foro / Comunidad' },
  { icon: 'import_contacts', label: 'Importar contactos' },
  { icon: 'import_export', label: 'Importar/Exportar' },
  { icon: 'invert_colors_off', label: 'Colores invertidos apagado' },
  { icon: 'list_alt', label: 'Lista alternativa' },
  { icon: 'live_help', label: 'Ayuda en vivo' },
  { icon: 'mail_outline', label: 'Correo contorno' },
  { icon: 'message', label: 'Mensaje' },
  { icon: 'mobile_screen_share', label: 'Compartir pantalla móvil' },
  { icon: 'no_sim', label: 'Sin SIM' },
  { icon: 'pause_presentation', label: 'Pausar presentación' },
  { icon: 'phone', label: 'Teléfono' },
  { icon: 'phonelink_erase', label: 'Borrar enlace teléfono' },
  { icon: 'phonelink_lock', label: 'Bloquear enlace teléfono' },
  { icon: 'phonelink_ring', label: 'Timbrar enlace teléfono' },
  { icon: 'phonelink_setup', label: 'Configurar enlace' },
  { icon: 'portable_wifi_off', label: 'WiFi portátil apagado' },
  { icon: 'present_to_all', label: 'Presentar a todos' },
  { icon: 'ring_volume', label: 'Volumen de timbre' },
  { icon: 'rss_feed', label: 'RSS / Noticias' },
  { icon: 'screen_share', label: 'Compartir pantalla' },
  { icon: 'sentiment_satisfied_alt', label: 'Satisfecho alternativo' },
  { icon: 'speaker_phone', label: 'Altavoz' },
  { icon: 'stay_current_landscape', label: 'Horizontal actual' },
  { icon: 'stay_current_portrait', label: 'Vertical actual' },
  { icon: 'stay_primary_landscape', label: 'Horizontal primario' },
  { icon: 'stay_primary_portrait', label: 'Vertical primario' },
  { icon: 'stop_screen_share', label: 'Detener pantalla compartida' },
  { icon: 'swap_calls', label: 'Intercambiar llamadas' },
  { icon: 'textsms', label: 'SMS / Texto' },
  { icon: 'unsubscribe', label: 'Cancelar suscripción' },
  { icon: 'voicemail', label: 'Buzón de voz' },
  { icon: 'vpn_key', label: 'Clave VPN' },
  { icon: '4k', label: '4K Ultra HD' },
  { icon: 'add_to_queue', label: 'Agregar a la cola' },
  { icon: 'airplay', label: 'AirPlay / Transmitir' },
  { icon: 'album', label: 'Álbum' },
  { icon: 'art_track', label: 'Pista de arte' },
  { icon: 'av_timer', label: 'Temporizador AV' },
  { icon: 'branding_watermark', label: 'Marca de agua' },
  { icon: 'call_to_action', label: 'Llamada a la acción' },
  { icon: 'closed_caption', label: 'Subtítulos cerrados' },
  { icon: 'control_camera', label: 'Control de cámara' },
  { icon: 'equalizer', label: 'Ecualizador' },
  { icon: 'explicit', label: 'Contenido explícito' },
  { icon: 'fast_forward', label: 'Avanzar rápido' },
  { icon: 'fast_rewind', label: 'Retroceder rápido' },
  { icon: 'featured_play_list', label: 'Lista destacada' },
  { icon: 'featured_video', label: 'Video destacado' },
  { icon: 'fiber_dvr', label: 'DVR' },
  { icon: 'fiber_manual_record', label: 'Grabación manual' },
  { icon: 'fiber_new', label: 'Nuevo (fibra)' },
  { icon: 'fiber_pin', label: 'PIN de fibra' },
  { icon: 'fiber_smart_record', label: 'Grabación inteligente' },
  { icon: 'forward_10', label: 'Adelantar 10s' },
  { icon: 'forward_30', label: 'Adelantar 30s' },
  { icon: 'forward_5', label: 'Adelantar 5s' },
  { icon: 'games', label: 'Juegos' },
  { icon: 'hd', label: 'Alta Definición' },
  { icon: 'hearing', label: 'Audición / Sonido' },
  { icon: 'high_quality', label: 'Alta calidad' },
  { icon: 'library_add', label: 'Agregar a biblioteca' },
  { icon: 'library_books', label: 'Biblioteca de libros' },
  { icon: 'library_music', label: 'Biblioteca de música' },
  { icon: 'loop', label: 'Repetir' },
  { icon: 'mic', label: 'Micrófono' },
  { icon: 'mic_none', label: 'Sin micrófono' },
  { icon: 'mic_off', label: 'Micrófono apagado' },
  { icon: 'missed_video_call', label: 'Videollamada perdida' },
  { icon: 'movie', label: 'Película' },
  { icon: 'music_note', label: 'Música en vivo' },
  { icon: 'music_video', label: 'Video musical' },
  { icon: 'new_releases', label: 'Nuevos lanzamientos' },
  { icon: 'not_interested', label: 'No interesado' },
  { icon: 'note', label: 'Nota musical' },
  { icon: 'pause', label: 'Pausar' },
  { icon: 'pause_circle_filled', label: 'Pausa círculo' },
  { icon: 'pause_circle_outline', label: 'Pausa círculo contorno' },
  { icon: 'play_arrow', label: 'Reproducir' },
  { icon: 'play_circle_filled', label: 'Reproducir círculo' },
  { icon: 'play_circle_outline', label: 'Reproducir contorno' },
  { icon: 'playlist_add', label: 'Agregar a lista' },
  { icon: 'playlist_add_check', label: 'Lista verificada' },
  { icon: 'playlist_play', label: 'Reproducir lista' },
  { icon: 'queue', label: 'Cola' },
  { icon: 'queue_music', label: 'Cola de música' },
  { icon: 'queue_play_next', label: 'Reproducir siguiente' },
  { icon: 'radio', label: 'Radio' },
  { icon: 'recent_actors', label: 'Actores recientes' },
  { icon: 'remove_from_queue', label: 'Quitar de la cola' },
  { icon: 'repeat', label: 'Repetir' },
  { icon: 'repeat_one', label: 'Repetir uno' },
  { icon: 'replay', label: 'Repetir' },
  { icon: 'replay_10', label: 'Repetir 10s' },
  { icon: 'replay_30', label: 'Repetir 30s' },
  { icon: 'replay_5', label: 'Repetir 5s' },
  { icon: 'shuffle', label: 'Aleatorio' },
  { icon: 'skip_next', label: 'Siguiente' },
  { icon: 'skip_previous', label: 'Anterior' },
  { icon: 'slow_motion_video', label: 'Video en cámara lenta' },
  { icon: 'snooze', label: 'Posponer' },
  { icon: 'sort_by_alpha', label: 'Ordenar alfabéticamente' },
  { icon: 'stop', label: 'Detener' },
  { icon: 'subscriptions', label: 'Suscripciones' },
  { icon: 'subtitles', label: 'Subtítulos' },
  { icon: 'surround_sound', label: 'Sonido envolvente' },
  { icon: 'video_call', label: 'Videollamada' },
  { icon: 'video_label', label: 'Etiqueta de video' },
  { icon: 'video_library', label: 'Biblioteca de video' },
  { icon: 'videocam', label: 'Videocámara' },
  { icon: 'videocam_off', label: 'Cámara apagada' },
  { icon: 'volume_down', label: 'Bajar volumen' },
  { icon: 'volume_mute', label: 'Silenciar volumen' },
  { icon: 'volume_off', label: 'Volumen apagado' },
  { icon: 'volume_up', label: 'Subir volumen' },
  { icon: 'add', label: 'Agregar' },
  { icon: 'add_box', label: 'Agregar caja' },
  { icon: 'add_circle', label: 'Agregar círculo' },
  { icon: 'add_circle_outline', label: 'Agregar círculo contorno' },
  { icon: 'archive', label: 'Archivar' },
  { icon: 'backspace', label: 'Retroceso' },
  { icon: 'ballot', label: 'Votación' },
  { icon: 'block', label: 'Bloquear' },
  { icon: 'clear', label: 'Limpiar' },
  { icon: 'create', label: 'Crear / Editar' },
  { icon: 'delete_sweep', label: 'Limpiar selección' },
  { icon: 'drafts', label: 'Borradores' },
  { icon: 'file_copy', label: 'Copiar archivo' },
  { icon: 'filter_list', label: 'Filtrar lista' },
  { icon: 'flag', label: 'Bandera / Marcar' },
  { icon: 'font_download', label: 'Descargar fuente' },
  { icon: 'forward', label: 'Reenviar' },
  { icon: 'gesture', label: 'Gesto' },
  { icon: 'how_to_reg', label: 'Cómo registrarse' },
  { icon: 'how_to_vote', label: 'Cómo votar' },
  { icon: 'inbox', label: 'Bandeja de entrada' },
  { icon: 'link', label: 'Enlace' },
  { icon: 'link_off', label: 'Sin enlace' },
  { icon: 'low_priority', label: 'Baja prioridad' },
  { icon: 'mail', label: 'Correo' },
  { icon: 'markunread', label: 'Marcar sin leer' },
  { icon: 'move_to_inbox', label: 'Mover a bandeja' },
  { icon: 'next_week', label: 'Próxima semana' },
  { icon: 'outlined_flag', label: 'Bandera contorno' },
  { icon: 'redo', label: 'Rehacer' },
  { icon: 'remove', label: 'Quitar' },
  { icon: 'remove_circle', label: 'Quitar círculo' },
  { icon: 'remove_circle_outline', label: 'Quitar círculo contorno' },
  { icon: 'reply', label: 'Responder' },
  { icon: 'reply_all', label: 'Responder a todos' },
  { icon: 'report', label: 'Reportar' },
  { icon: 'report_off', label: 'Sin reporte' },
  { icon: 'save', label: 'Guardar' },
  { icon: 'save_alt', label: 'Guardar alternativo' },
  { icon: 'select_all', label: 'Seleccionar todo' },
  { icon: 'send', label: 'Enviar' },
  { icon: 'sort', label: 'Ordenar' },
  { icon: 'text_format', label: 'Formato de texto' },
  { icon: 'unarchive', label: 'Desarchivar' },
  { icon: 'undo', label: 'Deshacer' },
  { icon: 'waves', label: 'Olas / Agua' },
  { icon: 'weekend', label: 'Fin de semana' },
  { icon: 'where_to_vote', label: 'Dónde votar' },
  { icon: 'access_alarm', label: 'Alarma acceso' },
  { icon: 'access_alarms', label: 'Alarmas' },
  { icon: 'access_time', label: 'Hora de acceso' },
  { icon: 'add_alarm', label: 'Agregar alarma' },
  { icon: 'add_to_home_screen', label: 'Agregar a inicio' },
  { icon: 'airplanemode_active', label: 'Modo avión activo' },
  { icon: 'airplanemode_inactive', label: 'Modo avión inactivo' },
  { icon: 'battery_alert', label: 'Alerta de batería' },
  { icon: 'battery_charging_full', label: 'Cargando batería' },
  { icon: 'battery_full', label: 'Batería llena' },
  { icon: 'battery_std', label: 'Batería estándar' },
  { icon: 'battery_unknown', label: 'Batería desconocida' },
  { icon: 'bluetooth', label: 'Bluetooth' },
  { icon: 'bluetooth_connected', label: 'Bluetooth conectado' },
  { icon: 'bluetooth_disabled', label: 'Bluetooth desactivado' },
  { icon: 'bluetooth_searching', label: 'Buscando Bluetooth' },
  { icon: 'brightness_auto', label: 'Brillo automático' },
  { icon: 'brightness_high', label: 'Brillo alto' },
  { icon: 'brightness_low', label: 'Brillo bajo' },
  { icon: 'brightness_medium', label: 'Brillo medio' },
  { icon: 'data_usage', label: 'Uso de datos' },
  { icon: 'developer_mode', label: 'Modo desarrollador' },
  { icon: 'devices', label: 'Dispositivos' },
  { icon: 'dvr', label: 'DVR' },
  { icon: 'gps_fixed', label: 'GPS fijo' },
  { icon: 'gps_not_fixed', label: 'GPS no fijo' },
  { icon: 'gps_off', label: 'GPS apagado' },
  { icon: 'graphic_eq', label: 'Ecualizador gráfico' },
  { icon: 'location_disabled', label: 'Ubicación desactivada' },
  { icon: 'location_searching', label: 'Buscando ubicación' },
  { icon: 'mobile_friendly', label: 'Amigable con móvil' },
  { icon: 'mobile_off', label: 'Móvil apagado' },
  { icon: 'network_cell', label: 'Red celular' },
  { icon: 'network_wifi', label: 'Red WiFi' },
  { icon: 'nfc', label: 'NFC' },
  { icon: 'screen_lock_landscape', label: 'Bloqueo horizontal' },
  { icon: 'screen_lock_portrait', label: 'Bloqueo vertical' },
  { icon: 'screen_lock_rotation', label: 'Bloqueo rotación' },
  { icon: 'screen_rotation', label: 'Rotación pantalla' },
  { icon: 'sd_storage', label: 'Almacenamiento SD' },
  { icon: 'settings_system_daydream', label: 'Protector de pantalla' },
  { icon: 'signal_cellular_4_bar', label: 'Señal celular 4 barras' },
  { icon: 'signal_cellular_alt', label: 'Señal celular alternativa' },
  { icon: 'signal_cellular_no_sim', label: 'Sin SIM' },
  { icon: 'signal_cellular_null', label: 'Sin señal' },
  { icon: 'signal_cellular_off', label: 'Señal apagada' },
  { icon: 'signal_wifi_4_bar', label: 'WiFi 4 barras' },
  { icon: 'signal_wifi_4_bar_lock', label: 'WiFi seguro' },
  { icon: 'signal_wifi_off', label: 'WiFi apagado' },
  { icon: 'storage', label: 'Almacenamiento' },
  { icon: 'usb', label: 'USB' },
  { icon: 'wallpaper', label: 'Fondo de pantalla' },
  { icon: 'widgets', label: 'Widgets' },
  { icon: 'wifi_lock', label: 'WiFi bloqueado' },
  { icon: 'wifi_tethering', label: 'Punto de acceso WiFi' },
  { icon: 'add_comment', label: 'Agregar comentario' },
  { icon: 'attach_file', label: 'Adjuntar archivo' },
  { icon: 'attach_money', label: 'Adjuntar dinero' },
  { icon: 'bar_chart', label: 'Gráfico de barras' },
  { icon: 'bubble_chart', label: 'Gráfico de burbujas' },
  { icon: 'drag_handle', label: 'Mango de arrastre' },
  { icon: 'format_align_center', label: 'Alinear centro' },
  { icon: 'format_align_justify', label: 'Justificar' },
  { icon: 'format_align_left', label: 'Alinear izquierda' },
  { icon: 'format_align_right', label: 'Alinear derecha' },
  { icon: 'format_bold', label: 'Negrita' },
  { icon: 'format_clear', label: 'Limpiar formato' },
  { icon: 'format_color_fill', label: 'Relleno de color' },
  { icon: 'format_color_reset', label: 'Restablecer color' },
  { icon: 'format_color_text', label: 'Color de texto' },
  { icon: 'format_indent_decrease', label: 'Disminuir sangría' },
  { icon: 'format_indent_increase', label: 'Aumentar sangría' },
  { icon: 'format_italic', label: 'Cursiva' },
  { icon: 'format_line_spacing', label: 'Espaciado de línea' },
  { icon: 'format_list_bulleted', label: 'Lista con viñetas' },
  { icon: 'format_list_numbered', label: 'Lista numerada' },
  { icon: 'format_list_numbered_rtl', label: 'Lista numerada RTL' },
  { icon: 'format_paint', label: 'Pintar formato' },
  { icon: 'format_quote', label: 'Cita' },
  { icon: 'format_shapes', label: 'Formas de formato' },
  { icon: 'format_size', label: 'Tamaño de fuente' },
  { icon: 'format_strikethrough', label: 'Tachado' },
  { icon: 'format_textdirection_l_to_r', label: 'Texto izquierda-derecha' },
  { icon: 'format_textdirection_r_to_l', label: 'Texto derecha-izquierda' },
  { icon: 'format_underlined', label: 'Subrayado' },
  { icon: 'functions', label: 'Funciones matemáticas' },
  { icon: 'highlight', label: 'Resaltar' },
  { icon: 'insert_chart', label: 'Insertar gráfico' },
  { icon: 'insert_chart_outlined', label: 'Gráfico contorno' },
  { icon: 'insert_comment', label: 'Insertar comentario' },
  { icon: 'insert_drive_file', label: 'Insertar archivo' },
  { icon: 'insert_emoticon', label: 'Insertar emoticono' },
  { icon: 'insert_invitation', label: 'Insertar invitación' },
  { icon: 'insert_link', label: 'Insertar enlace' },
  { icon: 'insert_photo', label: 'Insertar foto' },
  { icon: 'linear_scale', label: 'Escala lineal' },
  { icon: 'merge_type', label: 'Tipo de fusión' },
  { icon: 'mode_comment', label: 'Modo comentario' },
  { icon: 'monetization_on', label: 'Monetización' },
  { icon: 'money_off', label: 'Sin dinero' },
  { icon: 'multiline_chart', label: 'Gráfico multilínea' },
  { icon: 'notes', label: 'Notas' },
  { icon: 'pie_chart', label: 'Gráfico circular' },
  { icon: 'publish', label: 'Publicar' },
  { icon: 'scatter_plot', label: 'Gráfico de dispersión' },
  { icon: 'score', label: 'Puntuación' },
  { icon: 'short_text', label: 'Texto corto' },
  { icon: 'show_chart', label: 'Mostrar gráfico' },
  { icon: 'space_bar', label: 'Barra espaciadora' },
  { icon: 'strikethrough_s', label: 'Tachado S' },
  { icon: 'table_chart', label: 'Gráfico de tabla' },
  { icon: 'text_fields', label: 'Campos de texto' },
  { icon: 'title', label: 'Título' },
  { icon: 'vertical_align_bottom', label: 'Alinear abajo' },
  { icon: 'vertical_align_center', label: 'Alinear centro vertical' },
  { icon: 'vertical_align_top', label: 'Alinear arriba' },
  { icon: 'wrap_text', label: 'Ajustar texto' },
  { icon: 'attachment', label: 'Adjunto' },
  { icon: 'cloud', label: 'Nube' },
  { icon: 'cloud_circle', label: 'Nube círculo' },
  { icon: 'cloud_done', label: 'Nube lista' },
  { icon: 'cloud_download', label: 'Descargar de nube' },
  { icon: 'cloud_off', label: 'Sin nube' },
  { icon: 'cloud_queue', label: 'Cola de nube' },
  { icon: 'cloud_upload', label: 'Subir a nube' },
  { icon: 'create_new_folder', label: 'Nueva carpeta' },
  { icon: 'folder', label: 'Carpeta' },
  { icon: 'folder_open', label: 'Carpeta abierta' },
  { icon: 'folder_shared', label: 'Carpeta compartida' },
  { icon: 'cast', label: 'Transmitir' },
  { icon: 'cast_connected', label: 'Transmisión conectada' },
  { icon: 'computer', label: 'Computadora' },
  { icon: 'desktop_mac', label: 'iMac / Escritorio Mac' },
  { icon: 'desktop_windows', label: 'PC escritorio' },
  { icon: 'developer_board', label: 'Placa de desarrollo' },
  { icon: 'device_hub', label: 'Hub de dispositivos' },
  { icon: 'device_unknown', label: 'Dispositivo desconocido' },
  { icon: 'devices_other', label: 'Otros dispositivos' },
  { icon: 'dock', label: 'Dock' },
  { icon: 'gamepad', label: 'Mando de juego' },
  { icon: 'headset', label: 'Audífonos' },
  { icon: 'headset_mic', label: 'Audífonos con micrófono' },
  { icon: 'keyboard', label: 'Teclado' },
  { icon: 'keyboard_arrow_down', label: 'Flecha abajo teclado' },
  { icon: 'keyboard_arrow_left', label: 'Flecha izquierda teclado' },
  { icon: 'keyboard_arrow_right', label: 'Flecha derecha teclado' },
  { icon: 'keyboard_arrow_up', label: 'Flecha arriba teclado' },
  { icon: 'keyboard_backspace', label: 'Retroceso teclado' },
  { icon: 'keyboard_capslock', label: 'Bloq Mayús' },
  { icon: 'keyboard_hide', label: 'Ocultar teclado' },
  { icon: 'keyboard_return', label: 'Enter teclado' },
  { icon: 'keyboard_tab', label: 'Tab teclado' },
  { icon: 'keyboard_voice', label: 'Voz teclado' },
  { icon: 'laptop', label: 'Laptop' },
  { icon: 'laptop_chromebook', label: 'Chromebook' },
  { icon: 'laptop_mac', label: 'MacBook' },
  { icon: 'laptop_windows', label: 'Laptop Windows' },
  { icon: 'memory', label: 'Memoria RAM' },
  { icon: 'mouse', label: 'Ratón' },
  { icon: 'phone_android', label: 'Android' },
  { icon: 'phone_iphone', label: 'iPhone' },
  { icon: 'phonelink', label: 'Enlace de teléfono' },
  { icon: 'phonelink_off', label: 'Enlace de teléfono apagado' },
  { icon: 'power_input', label: 'Entrada de energía' },
  { icon: 'router', label: 'Router' },
  { icon: 'scanner', label: 'Escáner' },
  { icon: 'sim_card', label: 'Tarjeta SIM' },
  { icon: 'smartphone', label: 'Smartphone' },
  { icon: 'speaker', label: 'Bocina' },
  { icon: 'speaker_group', label: 'Grupo de bocinas' },
  { icon: 'tablet', label: 'Tablet' },
  { icon: 'tablet_android', label: 'Tablet Android' },
  { icon: 'tablet_mac', label: 'iPad' },
  { icon: 'toys', label: 'Juguetes / Hélice' },
  { icon: 'tv', label: 'Televisión' },
  { icon: 'videogame_asset', label: 'Consola de videojuegos' },
  { icon: 'watch', label: 'Reloj' },
  { icon: 'add_a_photo', label: 'Agregar foto' },
  { icon: 'add_photo_alternate', label: 'Foto alternativa' },
  { icon: 'add_to_photos', label: 'Agregar a fotos' },
  { icon: 'adjust', label: 'Ajustar' },
  { icon: 'assistant', label: 'Asistente' },
  { icon: 'assistant_photo', label: 'Foto asistente' },
  { icon: 'audiotrack', label: 'Pista de audio' },
  { icon: 'blur_circular', label: 'Desenfoque circular' },
  { icon: 'blur_linear', label: 'Desenfoque lineal' },
  { icon: 'blur_off', label: 'Sin desenfoque' },
  { icon: 'blur_on', label: 'Desenfoque activado' },
  { icon: 'broken_image', label: 'Imagen rota' },
  { icon: 'brush', label: 'Pincel' },
  { icon: 'burst_mode', label: 'Modo ráfaga' },
  { icon: 'camera', label: 'Cámara' },
  { icon: 'camera_alt', label: 'Cámara alternativa' },
  { icon: 'camera_front', label: 'Cámara frontal' },
  { icon: 'camera_rear', label: 'Cámara trasera' },
  { icon: 'camera_roll', label: 'Rollo de cámara' },
  { icon: 'center_focus_strong', label: 'Enfoque fuerte' },
  { icon: 'center_focus_weak', label: 'Enfoque débil' },
  { icon: 'collections', label: 'Colecciones' },
  { icon: 'collections_bookmark', label: 'Colección marcador' },
  { icon: 'color_lens', label: 'Lente de color' },
  { icon: 'colorize', label: 'Colorear' },
  { icon: 'compare', label: 'Comparar' },
  { icon: 'control_point', label: 'Punto de control' },
  { icon: 'control_point_duplicate', label: 'Duplicar punto' },
  { icon: 'crop', label: 'Recortar' },
  { icon: 'crop_free', label: 'Recorte libre' },
  { icon: 'crop_landscape', label: 'Recorte horizontal' },
  { icon: 'crop_portrait', label: 'Recorte vertical' },
  { icon: 'crop_square', label: 'Recorte cuadrado' },
  { icon: 'dehaze', label: 'Quitar neblina' },
  { icon: 'details', label: 'Detalles' },
  { icon: 'edit', label: 'Editar' },
  { icon: 'exposure', label: 'Exposición' },
  { icon: 'filter', label: 'Filtro' },
  { icon: 'filter_center_focus', label: 'Filtro enfoque centro' },
  { icon: 'filter_drama', label: 'Filtro dramático / Nubes' },
  { icon: 'filter_frames', label: 'Filtro marcos' },
  { icon: 'filter_hdr', label: 'Filtro montaña / HDR' },
  { icon: 'filter_none', label: 'Sin filtro' },
  { icon: 'filter_tilt_shift', label: 'Filtro inclinación' },
  { icon: 'filter_vintage', label: 'Filtro vintage' },
  { icon: 'flare', label: 'Destello' },
  { icon: 'flash_auto', label: 'Flash automático' },
  { icon: 'flash_off', label: 'Flash apagado' },
  { icon: 'flash_on', label: 'Flash encendido' },
  { icon: 'flip', label: 'Voltear imagen' },
  { icon: 'gradient', label: 'Degradado' },
  { icon: 'grain', label: 'Grano / Textura' },
  { icon: 'grid_off', label: 'Cuadrícula apagada' },
  { icon: 'grid_on', label: 'Cuadrícula encendida' },
  { icon: 'healing', label: 'Sanación / Retoque' },
  { icon: 'image', label: 'Imagen' },
  { icon: 'image_aspect_ratio', label: 'Relación de aspecto imagen' },
  { icon: 'image_search', label: 'Buscar imagen' },
  { icon: 'iso', label: 'ISO' },
  { icon: 'landscape', label: 'Paisaje / Vista' },
  { icon: 'lens', label: 'Lente' },
  { icon: 'linked_camera', label: 'Cámara vinculada' },
  { icon: 'looks', label: 'Looks / Apariencia' },
  { icon: 'loupe', label: 'Lupa' },
  { icon: 'monochrome_photos', label: 'Fotos monocromas' },
  { icon: 'movie_creation', label: 'Creación de película' },
  { icon: 'movie_filter', label: 'Filtro de película' },
  { icon: 'music_off', label: 'Música apagada' },
  { icon: 'nature', label: 'Naturaleza' },
  { icon: 'nature_people', label: 'Naturaleza y personas' },
  { icon: 'palette', label: 'Paleta de colores' },
  { icon: 'panorama', label: 'Panorama / Mirador' },
  { icon: 'panorama_fish_eye', label: 'Panorama ojo de pez' },
  { icon: 'panorama_horizontal', label: 'Panorama horizontal' },
  { icon: 'panorama_vertical', label: 'Panorama vertical' },
  { icon: 'panorama_wide_angle', label: 'Panorama gran angular' },
  { icon: 'photo', label: 'Foto' },
  { icon: 'photo_album', label: 'Álbum de fotos' },
  { icon: 'photo_camera', label: 'Cámara fotográfica' },
  { icon: 'photo_filter', label: 'Filtro de foto' },
  { icon: 'photo_library', label: 'Biblioteca de fotos' },
  { icon: 'picture_as_pdf', label: 'Imagen como PDF' },
  { icon: 'portrait', label: 'Retrato / Vertical' },
  { icon: 'remove_red_eye', label: 'Quitar ojos rojos' },
  { icon: 'rotate_left', label: 'Rotar izquierda' },
  { icon: 'rotate_right', label: 'Rotar derecha' },
  { icon: 'shutter_speed', label: 'Velocidad de obturador' },
  { icon: 'slideshow', label: 'Presentación de diapositivas' },
  { icon: 'straighten', label: 'Enderezar' },
  { icon: 'style', label: 'Estilo' },
  { icon: 'switch_camera', label: 'Cambiar cámara' },
  { icon: 'switch_video', label: 'Cambiar video' },
  { icon: 'tag_faces', label: 'Etiquetar caras' },
  { icon: 'texture', label: 'Textura' },
  { icon: 'timelapse', label: 'Tiempo transcurrido' },
  { icon: 'timer', label: 'Temporizador' },
  { icon: 'timer_off', label: 'Temporizador apagado' },
  { icon: 'tonality', label: 'Tonalidad' },
  { icon: 'transform', label: 'Transformar' },
  { icon: 'tune', label: 'Afinar / Ajustar' },
  { icon: 'view_comfy', label: 'Vista cómoda' },
  { icon: 'view_compact', label: 'Vista compacta' },
  { icon: 'vignette', label: 'Viñeta' },
  { icon: 'wb_auto', label: 'Balance de blancos auto' },
  { icon: 'wb_cloudy', label: 'Nublado / Luz difusa' },
  { icon: 'wb_incandescent', label: 'Luz incandescente' },
  { icon: 'wb_iridescent', label: 'Luz iridiscente' },
  { icon: 'wb_sunny', label: 'Luz solar / Al aire libre' },
  { icon: 'apps', label: 'Apps' },
  { icon: 'arrow_back', label: 'Atrás' },
  { icon: 'arrow_back_ios', label: 'Atrás iOS' },
  { icon: 'arrow_downward', label: 'Flecha abajo' },
  { icon: 'arrow_drop_down', label: 'Desplegar abajo' },
  { icon: 'arrow_drop_down_circle', label: 'Desplegar círculo' },
  { icon: 'arrow_drop_up', label: 'Desplegar arriba' },
  { icon: 'arrow_forward', label: 'Adelante' },
  { icon: 'arrow_forward_ios', label: 'Adelante iOS' },
  { icon: 'arrow_left', label: 'Flecha izquierda' },
  { icon: 'arrow_right', label: 'Flecha derecha' },
  { icon: 'arrow_upward', label: 'Flecha arriba' },
  { icon: 'cancel', label: 'Cancelar' },
  { icon: 'check', label: 'Verificar / Confirmar' },
  { icon: 'chevron_left', label: 'Chevron izquierda' },
  { icon: 'chevron_right', label: 'Chevron derecha' },
  { icon: 'close', label: 'Cerrar' },
  { icon: 'expand_less', label: 'Contraer' },
  { icon: 'expand_more', label: 'Expandir' },
  { icon: 'first_page', label: 'Primera página' },
  { icon: 'fullscreen', label: 'Pantalla completa' },
  { icon: 'fullscreen_exit', label: 'Salir pantalla completa' },
  { icon: 'last_page', label: 'Última página' },
  { icon: 'menu', label: 'Menú' },
  { icon: 'more_horiz', label: 'Más horizontal' },
  { icon: 'more_vert', label: 'Más vertical' },
  { icon: 'refresh', label: 'Refrescar' },
  { icon: 'subdirectory_arrow_left', label: 'Subdirectorio izquierda' },
  { icon: 'subdirectory_arrow_right', label: 'Subdirectorio derecha' },
  { icon: 'unfold_less', label: 'Contraer todo' },
  { icon: 'unfold_more', label: 'Expandir todo' },
  { icon: 'adb', label: 'ADB / Android Debug' },
  { icon: 'airline_seat_flat', label: 'Asiento plano (cama)' },
  { icon: 'airline_seat_flat_angled', label: 'Asiento inclinado' },
  { icon: 'airline_seat_individual_suite', label: 'Suite individual' },
  { icon: 'airline_seat_legroom_extra', label: 'Espacio extra piernas' },
  { icon: 'airline_seat_legroom_normal', label: 'Espacio normal piernas' },
  { icon: 'airline_seat_legroom_reduced', label: 'Espacio reducido piernas' },
  { icon: 'airline_seat_recline_extra', label: 'Reclinación extra' },
  { icon: 'airline_seat_recline_normal', label: 'Reclinación normal' },
  { icon: 'bluetooth_audio', label: 'Audio Bluetooth' },
  { icon: 'confirmation_number', label: 'Número de confirmación' },
  { icon: 'disc_full', label: 'Disco lleno' },
  { icon: 'drive_eta', label: 'ETA de viaje' },
  { icon: 'enhanced_encryption', label: 'Cifrado mejorado' },
  { icon: 'event_available', label: 'Evento disponible' },
  { icon: 'event_busy', label: 'Evento ocupado' },
  { icon: 'event_note', label: 'Nota de evento' },
  { icon: 'folder_special', label: 'Carpeta especial' },
  { icon: 'live_tv', label: 'TV en vivo' },
  { icon: 'mms', label: 'MMS / Multimedia' },
  { icon: 'network_check', label: 'Verificar red' },
  { icon: 'network_locked', label: 'Red bloqueada' },
  { icon: 'no_encryption', label: 'Sin cifrado' },
  { icon: 'ondemand_video', label: 'Video a demanda' },
  { icon: 'personal_video', label: 'Video personal' },
  { icon: 'phone_bluetooth_speaker', label: 'Altavoz Bluetooth' },
  { icon: 'phone_callback', label: 'Devolución de llamada' },
  { icon: 'phone_forwarded', label: 'Llamada reenviada' },
  { icon: 'phone_in_talk', label: 'En llamada' },
  { icon: 'phone_locked', label: 'Teléfono bloqueado' },
  { icon: 'phone_missed', label: 'Llamada perdida' },
  { icon: 'phone_paused', label: 'Llamada en pausa' },
  { icon: 'power', label: 'Energía' },
  { icon: 'power_off', label: 'Sin energía' },
  { icon: 'priority_high', label: 'Alta prioridad' },
  { icon: 'sd_card', label: 'Tarjeta SD' },
  { icon: 'sms', label: 'SMS' },
  { icon: 'sms_failed', label: 'SMS fallido' },
  { icon: 'sync', label: 'Sincronizar' },
  { icon: 'sync_disabled', label: 'Sincronización desactivada' },
  { icon: 'sync_problem', label: 'Problema de sincronización' },
  { icon: 'system_update', label: 'Actualización del sistema' },
  { icon: 'tap_and_play', label: 'Tocar y reproducir' },
  { icon: 'time_to_leave', label: 'Hora de salir' },
  { icon: 'tv_off', label: 'TV apagada' },
  { icon: 'vibration', label: 'Vibración' },
  { icon: 'voice_chat', label: 'Chat de voz' },
  { icon: 'vpn_lock', label: 'VPN bloqueada' },
  { icon: 'wc', label: 'Baños / Servicios' },
  { icon: 'wifi', label: 'WiFi' },
  { icon: 'wifi_off', label: 'WiFi apagado' },
  { icon: 'check_box', label: 'Casilla marcada' },
  { icon: 'check_box_outline_blank', label: 'Casilla vacía' },
  { icon: 'indeterminate_check_box', label: 'Casilla indeterminada' },
  { icon: 'radio_button_checked', label: 'Radio marcado' },
  { icon: 'radio_button_unchecked', label: 'Radio desmarcado' },
  { icon: 'star', label: 'Estrella' },
  { icon: 'star_border', label: 'Estrella contorno' },
  { icon: 'star_half', label: 'Media estrella' },
  { icon: 'add_alert', label: 'Agregar alerta' },
  { icon: 'error', label: 'Error' },
  { icon: 'error_outline', label: 'Error contorno' },
  { icon: 'notification_important', label: 'Notificación importante' },
  { icon: 'warning', label: 'Advertencia' },
  { icon: 'cake', label: 'Cumpleaños / Celebración' },
  { icon: 'domain', label: 'Dominio / Empresa' },
  { icon: 'group', label: 'Grupo' },
  { icon: 'group_add', label: 'Agregar grupo' },
  { icon: 'location_city', label: 'Ciudad' },
  { icon: 'mood', label: 'Buen ánimo' },
  { icon: 'mood_bad', label: 'Mal ánimo' },
  { icon: 'notifications', label: 'Notificaciones' },
  { icon: 'notifications_active', label: 'Notificaciones activas' },
  { icon: 'notifications_none', label: 'Sin notificaciones' },
  { icon: 'notifications_off', label: 'Notificaciones apagadas' },
  { icon: 'notifications_paused', label: 'Notificaciones pausadas' },
  { icon: 'pages', label: 'Páginas' },
  { icon: 'party_mode', label: 'Modo fiesta' },
  { icon: 'people', label: 'Personas / Grupo' },
  { icon: 'people_outline', label: 'Personas contorno' },
  { icon: 'person', label: 'Persona' },
  { icon: 'person_add', label: 'Agregar persona' },
  { icon: 'person_outline', label: 'Persona contorno' },
  { icon: 'plus_one', label: '+1' },
  { icon: 'poll', label: 'Encuesta' },
  { icon: 'public', label: 'Público / Internet' },
  { icon: 'school', label: 'Escuela / Educación' },
  { icon: 'sentiment_dissatisfied', label: 'Insatisfecho' },
  { icon: 'sentiment_satisfied', label: 'Satisfecho' },
  { icon: 'sentiment_very_dissatisfied', label: 'Muy insatisfecho' },
  { icon: 'sentiment_very_satisfied', label: 'Muy satisfecho' },
  { icon: 'share', label: 'Compartir' },
  { icon: 'thumb_down_alt', label: 'No me gusta' },
  { icon: 'thumb_up_alt', label: 'Me gusta' },
  { icon: 'whatshot', label: 'Tendencia / Popular' }
];
